### ISSUE TITLE
Add ability to start/stop chameleonsocks

### ISSUE THREAD

**Issue by whbruce** [todorez/chameleonsocks#2]
Add --start and --stop options to chameleonsocks script

**Comment by todorez** [comment]
Implemented with 8b3b3dbecb071c4de8431d4ea21d02898a576895

The following parameters can be used with chameleonsocks:

--install      : Install chameleonsocks
--upgrade      : Upgrade existing installation
--uninstall    : Uninstall chameleonsocks
--install-ui   : Install container management UI
--uninstall-ui : Uninstall container management UI
--start        : Stop chameleonsocks
--stop         : Start chameleonsocks
--version      : Display chameleonsocks version
